name: On after merge workflow
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - .github/**

  workflow_dispatch:
    inputs:
      modules_to_build:
        required: true
        description: "The modules to build when running from the root of the project. Defaults to everything ('.')"
        default: "."

jobs:

  reusable-merge-workflow:
    uses: pentaho/actions-common/.github/workflows/merge.yml@DEVO-11809
    with:
      modules_to_build: ${{ inputs.modules_to_build }}
    secrets: inherit
